CREATE TABLE IF NOT EXISTS issues (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description TEXT NOT NULL,
created_by VARCHAR(100) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT now(),
updated_by VARCHAR(100),
updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS issue_revisions (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
issue_id INT(6) UNSIGNED NOT NULL,
CONSTRAINT FK_IssueRevision FOREIGN KEY (issue_id) REFERENCES issues(id),
changes JSON NULL,
updated_at TIMESTAMP NOT NULL DEFAULT now()
);
